"""Build an offline HTML gallery and integrity manifest; never modify poster pixels."""
from pathlib import Path
import hashlib
import html
import json
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
TITLES = {
    'material-series': [
        '从思维出发，让代码发光', '学会编程，从理解开始', '让想法，一步步成为程序',
        '一半思维，一半代码', '把复杂问题，拆成清晰步骤', '生活里的难题，也有算法',
        '从一个像素，看懂数字世界', '两个数字，打开新的世界', '你的 Python，从这一页开始',
        '变量与数据命名', '认识数据类型', 'if：让程序懂得选择', '把重复交给循环',
        '用函数组织过程', '先建立逻辑，再编程', '引导式学习', '为解决问题，多一种思路', '翻开书，开始编程',
    ],
    'esther-series': [
        '把思考，写成代码', '两篇内容，从思维到代码', '提问、拆解、实践', '先理解，再动手',
        '为解决问题，多一种思路', 'Python 学习路线', '从生活中，发现算法',
        '一步一步，读懂 Python', '给好奇心，一个起点', '翻开书，让想法开始运行',
    ],
}
manifest = []
sections = []
for group, titles in TITLES.items():
    paths = sorted((ROOT / group).glob('*.png'))
    if len(paths) != len(titles):
        raise ValueError(f'{group}: expected {len(titles)} images, found {len(paths)}')
    figures = []
    for path, title in zip(paths, titles):
        data = path.read_bytes()
        assert data[:8] == b'\x89PNG\r\n\x1a\n', path
        width, height = struct.unpack('>II', data[16:24])
        assert width > height and abs(width / height - 16 / 9) < .01, path
        rel = path.relative_to(ROOT).as_posix()
        manifest.append(dict(file=rel, title=title, width=width, height=height,
                             bytes=len(data), sha256=hashlib.sha256(data).hexdigest()))
        number = path.name[:2]
        figures.append(f'''<figure>
  <a class="poster" href="{rel}" data-title="{html.escape(title)}"><img src="{rel}" alt="{html.escape(title)}" width="{width}" height="{height}" loading="lazy"></a>
  <figcaption><span>{number} / {html.escape(title)}</span><a class="download" href="{rel}" download>下载 PNG ↗</a></figcaption>
</figure>''')
    name = '书籍主题 · 18 张' if group == 'material-series' else 'Esther 设计系统 · 10 张'
    note = '暖金与墨黑，延续书封的光与质感。' if group == 'material-series' else '奶油纸底、手绘批注与衬线大字，配合深棕、金黄和朱红。'
    sections.append(f'<section id="{group}"><header class="series"><h2>{name}</h2><p>{note}</p></header><div class="gallery">'+ '\n'.join(figures) +'</div></section>')

# Adapt the supplied Esther template's variable system, reset, serif/sans hierarchy.
reference = (ROOT / 'source/esther-template-reference.html').read_text()
variables = re.search(r':root\s*\{[^}]+\}', reference).group()
document = '''<!DOCTYPE html>
<!-- Based on template-cards.html by ESTHER不二 (esthersjw). CC BY-NC-SA 4.0.
     https://github.com/esthersjw/esther-design-system
     Poster pixels and all in-poster text are generated by built-in imagegen. -->
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>编程启蒙：思维与代码 · 28 张横版海报</title><style>
* { margin:0; padding:0; box-sizing:border-box; }
VARIABLES
body { background:var(--cream); color:var(--blue); font-family:'Noto Sans SC','PingFang SC','Microsoft YaHei',sans-serif; }
::selection { background:var(--yellow); color:var(--ink); }
a { color:inherit; text-underline-offset:5px; } a:hover { text-decoration-thickness:3px; }
button { font:inherit; cursor:pointer; }
.wrap { max-width:1480px; padding:clamp(24px,5vw,72px); margin:auto; }
.intro { display:grid; grid-template-columns:1fr auto; gap:40px; padding-block:32px 52px; border-bottom:1px solid #d7cdbb; }
.eyebrow { font-size:12px; letter-spacing:.15em; margin-bottom:22px; }
h1,h2 { font-family:'Noto Serif SC','Songti SC','STSong',serif; font-weight:900; }
h1 { font-size:clamp(34px,5vw,72px); line-height:1.3; }
.intro p { margin-top:20px; line-height:1.8; color:var(--ink-light); max-width:52em; }
.count { font-family:'Fraunces',Georgia,serif; font-style:italic; font-size:clamp(90px,13vw,180px); line-height:1; color:var(--yellow); }
nav { display:flex; flex-wrap:wrap; gap:12px; margin-block:28px 48px; }
nav a { padding:12px 18px; background:var(--cream-dark); text-decoration:none; border:1px solid #d7cdbb; }
nav a:hover { background:var(--yellow); }
.series { display:flex; align-items:baseline; justify-content:space-between; gap:24px; margin-bottom:24px; }
h2 { font-size:clamp(24px,3vw,36px); } .series p { font-size:14px; line-height:1.7; color:var(--ink-light); }
section + section { margin-top:clamp(70px,10vw,120px); }
.gallery { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:40px 24px; }
figure { min-width:0; } .poster { display:block; background:var(--cream-dark); }
img { display:block; width:100%; height:auto; } .poster:focus-visible { outline:4px solid var(--red); outline-offset:5px; }
figcaption { display:flex; gap:12px; justify-content:space-between; align-items:baseline; padding-top:13px; font-size:13px; line-height:1.6; }
.download { flex-shrink:0; color:#785724; font-size:12px; }
footer { margin-top:80px; padding-block:28px; border-top:1px solid #d7cdbb; font-size:12px; line-height:1.9; color:var(--ink-light); }
dialog { border:0; padding:20px; background:var(--cream); color:var(--blue); width:min(96vw,1700px); max-width:96vw; max-height:96vh; margin:auto; }
dialog::backdrop { background:rgb(28 23 18 / .86); } dialog img { max-height:80vh; object-fit:contain; }
.viewer-bar { display:flex; align-items:center; gap:16px; padding-top:16px; } .viewer-bar span { margin-right:auto; }
.viewer-bar button { background:var(--blue); color:var(--cream); border:0; padding:10px 14px; }
@media(max-width:900px) { .intro { grid-template-columns:1fr; } .count { display:none; } .gallery { grid-template-columns:1fr; } .series { display:block; } .series p { margin-top:12px; } }
@media(max-width:600px) { figcaption { flex-direction:column; gap:5px; } .viewer-bar { flex-wrap:wrap; } .viewer-bar span { width:100%; } }
@media(prefers-reduced-motion:reduce) { * { scroll-behavior:auto !important; } }
</style></head><body><main class="wrap">
<header class="intro"><div><div class="eyebrow">AI悦创 / BOOK POSTERS / 2026.09.15</div><h1>编程启蒙：<br>思维与代码</h1><p>28 张独立横版海报。点击图片可放大，使用左右方向键切换；每张均可下载原生 PNG。</p></div><div class="count" aria-hidden="true">28</div></header>
<nav aria-label="海报系列"><a href="#material-series">书籍主题 · 18 张</a><a href="#esther-series">Esther · 10 张</a><a href="README.md">设计说明</a><a href="PROMPTS.md">提示词记录</a></nav>
SECTIONS
<footer>书籍：黄家宝《编程启蒙：思维与代码》 / 北京航空航天大学出版社。<br>
Esther 系列及本画廊采用 <a href="https://github.com/esthersjw/esther-design-system">ESTHER不二（esthersjw）的设计系统</a>，署名与适用范围见 <a href="ATTRIBUTION.md">CC BY-NC-SA 4.0 说明</a>。<br>
画面及图中文字均通过内置 imagegen 生成，完整提示词与来源见 source/。保留原生尺寸，未进行后期叠字。</footer>
</main>
<dialog id="viewer" aria-label="海报大图"><img id="large" alt=""><div class="viewer-bar"><span id="caption"></span><button id="prev" aria-label="上一张">←</button><button id="next" aria-label="下一张">→</button><a id="download-large" download>下载 PNG</a><button id="close">关闭 ×</button></div></dialog>
<script>
const links=[...document.querySelectorAll('.poster')], viewer=document.querySelector('#viewer');
let current=0;
function show(i){current=(i+links.length)%links.length;const link=links[current];document.querySelector('#large').src=link.href;document.querySelector('#large').alt=link.dataset.title;document.querySelector('#caption').textContent=(current+1)+' / '+links.length+' · '+link.dataset.title;document.querySelector('#download-large').href=link.href;if(!viewer.open)viewer.showModal();}
links.forEach((link,i)=>link.addEventListener('click',event=>{event.preventDefault();show(i);}));
document.querySelector('#close').onclick=()=>viewer.close();document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);
viewer.addEventListener('click',event=>{if(event.target===viewer){const r=viewer.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)viewer.close();}});
document.addEventListener('keydown',event=>{if(!viewer.open)return;if(event.key==='ArrowLeft'){event.preventDefault();show(current-1);}if(event.key==='ArrowRight'){event.preventDefault();show(current+1);}});
</script></body></html>'''.replace('VARIABLES', variables).replace('SECTIONS', '\n'.join(sections))
(ROOT / 'gallery.html').write_text(document)
(ROOT / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n')
(ROOT / 'SHA256SUMS.txt').write_text(''.join(f"{item['sha256']}  {item['file']}\n" for item in manifest))
print(f'Built gallery and manifest for {len(manifest)} original PNGs.')
