/* ImageGen originals; this manifest supplies gallery captions, never image typography. */
window.POSTERS = [
  { id: 'M01', series: 'material', file: '01-golden-first-page.png', title: '翻开书，让思维先出发', style: '黑金 · 编辑式开篇' },
  { id: 'M02', series: 'material', file: '02-thought-to-code.png', title: '把想法，写成代码', style: '暖色 · 积木与纸带' },
  { id: 'M03', series: 'material', file: '03-begin-with-curiosity.png', title: '零基础，从好奇开始', style: '明亮 · 极简提问' },
  { id: 'M04', series: 'material', file: '04-logic-before-syntax.png', title: '代码之前，先有思路', style: '墨绿 · 杂志大字' },
  { id: 'M05', series: 'material', file: '05-python-path.png', title: '走进 Python 的第一程', style: '地图 · 横向旅程' },
  { id: 'M06', series: 'material', file: '06-everyday-algorithms.png', title: '生活里，藏着算法', style: '桌面 · 日常顺序' },
  { id: 'M07', series: 'material', file: '07-beyond-memorizing.png', title: '不只记语法，更要会思考', style: '双栏 · 思考与练习' },
  { id: 'M08', series: 'material', file: '08-five-thinking-tools.png', title: '给思维，多一套工具', style: '工具 · 抽象构图' },
  { id: 'M09', series: 'material', file: '09-build-from-small.png', title: '大问题，从小步骤开始', style: '纸艺 · 拆解阶梯' },
  { id: 'M10', series: 'material', file: '10-reading-companion.png', title: '让好奇心，有书相伴', style: '角色 · 温暖阅读' },
  { id: 'M11', series: 'material', file: '11-quiet-learning-desk.png', title: '留一点时间，给新的可能', style: '静物 · 学习书桌' },
  { id: 'M12', series: 'material', file: '12-think-then-practice.png', title: '想明白，再动手', style: '橙色 · 大字草稿' },
  { id: 'M13', series: 'material', file: '13-first-line.png', title: '从第一行，走向自己的想法', style: '纸面 · 代码起点' },
  { id: 'M14', series: 'material', file: '14-two-part-journey.png', title: '一半是思维，一半是代码', style: '拼接 · 双篇叙事' },
  { id: 'M15', series: 'material', file: '15-learning-your-way.png', title: '找到适合你的编程起点', style: '书架 · 编辑排版' },
  { id: 'M16', series: 'material', file: '16-questions-to-solutions.png', title: '好问题，是学习的开始', style: '角色 · 几何问号' },
  { id: 'M17', series: 'material', file: '17-read-and-explore.png', title: '翻开一页，探索一步', style: '俯拍 · 阅读探索' },
  { id: 'M18', series: 'material', file: '18-start-today.png', title: '今天，开始理解编程', style: '极简 · 开始邀请' },
  { id: 'E01', series: 'esther', file: '01-esther-editorial-cover.png', title: '先打开思维，再打开代码', style: 'Esther · 暖纸封面' },
  { id: 'E02', series: 'esther', file: '02-esther-question.png', title: '学编程，从一个好问题开始', style: 'Esther · 超大问号' },
  { id: 'E03', series: 'esther', file: '03-esther-two-chapters.png', title: '思维打底，代码落地', style: 'Esther · 跨页双栏' },
  { id: 'E04', series: 'esther', file: '04-esther-thinking-toolkit.png', title: '把思维，练成你的工具', style: 'Esther · 手绘索引' },
  { id: 'E05', series: 'esther', file: '05-esther-small-steps.png', title: '复杂的问题，一步步来', style: 'Esther · 横向阶梯' },
  { id: 'E06', series: 'esther', file: '06-esther-reading-note.png', title: '慢慢读，认真想，动手试', style: 'Esther · 阅读手记' },
  { id: 'E07', series: 'esther', file: '07-esther-python-start.png', title: '你的 Python，从这里开始', style: 'Esther · 超大编号' },
  { id: 'E08', series: 'esther', file: '08-esther-idea-to-action.png', title: '让想法，多一种表达', style: 'Esther · 手写便签' },
  { id: 'E09', series: 'esther', file: '09-esther-learning-companion.png', title: '和好奇心，一起长大', style: 'Esther · 角色留白' },
  { id: 'E10', series: 'esther', file: '10-esther-closing-invitation.png', title: '下一页，写下你的可能', style: 'Esther · 书籍邀请' }
];
